### ISSUE TITLE
how do I generate file_v2.json1 in augment_data.py ?

### ISSUE THREAD

**Issue by Michelle-Mings** [gunturbudi/ner-privacy-engineering#2]
what does the file look like? I know it should at least have "text" and "labels" but I am not sure of their type or data schema. Thanks.

**Comment by gunturbudi** [comment]
Hello, the file is jsonline, generated by doccano annotation tools. Here are the first 4 data and the line of the file. The rest should be the same:

`
{"id": 1515, "text": "As a moderator, I want to create a new game by entering a name and an optional description, so that I can start inviting estimators.", "meta": {}, "annotation_approver": null, "labels": [[58, 62, "PII"], [5, 14, "Data Subject"], [47, 55, "Processing"], [112, 120, "Processing"], [121, 131, "Data Subject"], [70, 90, "PII"]]}
`
`
{"id": 1516, "text": "As a moderator, I want to invite estimators by giving them a URL where they can access the game, so that we can start the game.", "meta": {}, "annotation_approver": null, "labels": [[5, 14, "Data Subject"], [33, 43, "Data Subject"], [26, 32, "Processing"]]}
`
`
{"id": 1517, "text": "As a moderator, I want to start a round by entering an item in a single multi-line text field, so that we can estimate it.", "meta": {}, "annotation_approver": null, "labels": [[5, 14, "Data Subject"]]}
`
`
{"id": 1518, "text": "As a moderator, I want to see all items we try to estimate this session, so that I can answer questions about the current story such as \"does this include ___\".", "meta": {}, "annotation_approver": null, "labels": [[64, 71, "PII"], [94, 103, "PII"], [5, 14, "Data Subject"]]}
`

Hope it helps!

**Comment by Michelle-Mings** [comment]
Thank you for providing the context. This helps a lot!
